import saveAs from 'file-saver';
// Removed static imports of jsPDF and html2canvas for Code Splitting
import { EnhancementOptions } from '../types';
import { logger } from './errorLogging';

export type ExportScope = 'all' | 'enhanced' | 'original';

interface ExportData {
  input: string;
  output: string;
  options: EnhancementOptions;
  scope: ExportScope;
}

const generateMetaString = (options: EnhancementOptions, timestamp: string) => {
  return `
---
Generated by: DevPrompt Studio
Timestamp: ${timestamp}
Domain: ${options.domain}
Tool: ${options.targetTool}
Platform: ${options.platform}
Complexity: ${options.complexity}
---
`;
};

export const exportMarkdown = (data: ExportData) => {
  try {
    const timestamp = new Date().toLocaleString();
    let content = "";
    
    if (data.scope === 'all') {
        content = `# Enhanced Prompt Specification
${generateMetaString(data.options, timestamp)}

## Original Input
${data.input}

## Enhanced Output
${data.output}
`;
    } else if (data.scope === 'enhanced') {
        content = `# Enhanced Prompt
${generateMetaString(data.options, timestamp)}

${data.output}
`;
    } else if (data.scope === 'original') {
        content = `# Original Input
${generateMetaString(data.options, timestamp)}

${data.input}
`;
    }

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    saveAs(blob, `devprompt-${data.scope}-${Date.now()}.md`);
    logger.info('Export Success', { format: 'markdown', scope: data.scope });
  } catch (e: any) {
    logger.error(new Error('Export Failed'), { format: 'markdown', error: e.message });
  }
};

export const exportJSON = (data: ExportData) => {
  try {
    const baseObj = {
      meta: {
        generator: "DevPrompt Studio",
        timestamp: new Date().toISOString(),
        version: "1.0",
        scope: data.scope,
        options: data.options
      }
    };

    let exportObj: any = { ...baseObj };

    if (data.scope === 'all') {
        exportObj.input = data.input;
        exportObj.output = data.output;
    } else if (data.scope === 'enhanced') {
        exportObj.content = data.output;
    } else if (data.scope === 'original') {
        exportObj.content = data.input;
    }

    const content = JSON.stringify(exportObj, null, 2);
    const blob = new Blob([content], { type: 'application/json;charset=utf-8' });
    saveAs(blob, `devprompt-${data.scope}-${Date.now()}.json`);
    logger.info('Export Success', { format: 'json', scope: data.scope });
  } catch (e: any) {
    logger.error(new Error('Export Failed'), { format: 'json', error: e.message });
  }
};

export const exportText = (data: ExportData) => {
  try {
    const timestamp = new Date().toLocaleString();
    let content = `DEVPROMPT STUDIO EXPORT (${data.scope.toUpperCase()})
-----------------------
Date: ${timestamp}
Configuration: ${data.options.domain} / ${data.options.targetTool}
\n`;

    if (data.scope === 'all') {
        content += `ORIGINAL INPUT:
${data.input}

ENHANCED OUTPUT:
${data.output}`;
    } else if (data.scope === 'enhanced') {
        content += `${data.output}`;
    } else if (data.scope === 'original') {
        content += `${data.input}`;
    }

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    saveAs(blob, `devprompt-${data.scope}-${Date.now()}.txt`);
    logger.info('Export Success', { format: 'text', scope: data.scope });
  } catch (e: any) {
    logger.error(new Error('Export Failed'), { format: 'text', error: e.message });
  }
};

export const exportPDF = async (element: HTMLElement, options: EnhancementOptions) => {
  try {
    // Dynamic Imports for Code Splitting
    const html2canvas = (await import('html2canvas')).default;
    const { jsPDF } = await import('jspdf');

    // 1. Capture the element as canvas
    const canvas = await html2canvas(element, {
      scale: 2, // High resolution
      backgroundColor: '#0f172a', // Match theme
      logging: false,
      useCORS: true
    });

    // 2. Initialize PDF
    const imgData = canvas.toDataURL('image/png');
    // jsPDF default export is a class constructor
    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });

    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = pdf.internal.pageSize.getHeight();
    const imgWidth = pdfWidth;
    const imgHeight = (canvas.height * pdfWidth) / canvas.width;

    // 3. Add Header Info
    pdf.setFillColor(15, 23, 42); // Slate 900
    pdf.rect(0, 0, pdfWidth, pdfHeight, 'F'); // Background
    
    // Add Content Image
    let heightLeft = imgHeight;
    let position = 0;
    
    // First page
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pdfHeight;

    // Subsequent pages
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.setFillColor(15, 23, 42);
      pdf.rect(0, 0, pdfWidth, pdfHeight, 'F');
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pdfHeight;
    }

    // Add Footer Metadata
    const date = new Date().toLocaleString();
    pdf.setFontSize(8);
    pdf.setTextColor(100, 116, 139); // Slate 500
    pdf.text(`DevPrompt Studio | Generated: ${date} | Config: ${options.targetTool}`, 10, pdfHeight - 10);

    pdf.save(`devprompt-export-${Date.now()}.pdf`);
    logger.info('Export Success', { format: 'pdf', scope: 'visual-snapshot' });
  } catch (e: any) {
    console.error(e);
    logger.error(new Error('PDF Export Failed'), { format: 'pdf', error: e.message });
    throw e; // Re-throw to show toast
  }
};