import { trackEvent } from './analytics';

export const exportMarkdown = (data: any) => {
  const content = `# Prompt Enhancement

## Original Prompt
${data.input}

## Enhanced Prompt
${data.output}

---
*Generated by DevPrompt Studio*
`;
  downloadFile(content, 'prompt.md', 'text/markdown');
};

export const exportJSON = (data: any) => {
  const content = JSON.stringify({
    original: data.input,
    enhanced: data.output,
    options: data.options,
    timestamp: Date.now(),
    version: '1.0'
  }, null, 2);
  downloadFile(content, 'prompt.json', 'application/json');
};

export const exportText = (data: any) => {
  const content = `${data.input}\n\n---\n\n${data.output}`;
  downloadFile(content, 'prompt.txt', 'text/plain');
};

export const exportPDF = async (element: HTMLElement, options: any) => {
  // Placeholder for PDF export - requires html2canvas + jspdf
  const content = element.innerText;
  downloadFile(content, 'prompt.pdf', 'application/pdf');
};

const downloadFile = (content: string, filename: string, type: string) => {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  
  trackEvent('prompt_exported', { format: filename.split('.').pop() });
};

export const copyToClipboard = async (text: string) => {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    // Fallback
    const textarea = document.createElement('textarea');
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand('copy');
    document.body.removeChild(textarea);
    return true;
  }
};
